# -*- coding: utf-8 -*-
"""Number plate recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jPGMitO4xnUOcSxy_dZYcC4ovzL8gpXu
"""

!apt-get install -y tesseract-ocr
!pip install pytesseract opencv-python matplotlib

from google.colab import files
uploaded = files.upload()

import cv2
import pytesseract
import numpy as np
import re
from matplotlib import pyplot as plt
from google.colab.patches import cv2_imshow

# get uploaded filename
image_name = list(uploaded.keys())[0]

print("Processing:", image_name)

# Read image
image = cv2.imread(image_name)

if image is None:
    print("Image not loaded properly")
else:
    image = cv2.resize(image, (600,400))

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    gray = cv2.bilateralFilter(gray,11,17,17)

    edged = cv2.Canny(gray,30,200)

    contours,_ = cv2.findContours(
        edged.copy(),
        cv2.RETR_TREE,
        cv2.CHAIN_APPROX_SIMPLE
    )

    contours = sorted(contours,
                      key=cv2.contourArea,
                      reverse=True)[:10]

    number_plate=None

    for contour in contours:
        peri=cv2.arcLength(contour,True)
        approx=cv2.approxPolyDP(contour,0.018*peri,True)

        if len(approx)==4:
            number_plate=approx
            break

    if number_plate is None:
        print("Number plate not detected")

    else:
        mask=np.zeros(gray.shape,np.uint8)
        cv2.drawContours(mask,[number_plate],0,255,-1)

        x,y=np.where(mask==255)

        topx,topy=np.min(x),np.min(y)
        bottomx,bottomy=np.max(x),np.max(y)

        cropped=gray[topx:bottomx+1,
                     topy:bottomy+1]

        _, thresh = cv2.threshold(cropped, 150, 255, cv2.THRESH_BINARY)

        custom_config = r'--oem 3 --psm 8 -c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

        text = pytesseract.image_to_string(thresh, config=custom_config)
        text=re.sub('[^A-Z0-9]','',text.upper())

        print("Detected Plate:",text)

        plt.imshow(cropped,cmap="gray")
        plt.axis("off")
        plt.show()